// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class PositiveaddchillplaceTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void positiveaddchillplace() {
    driver.Navigate().GoToUrl("http://localhost:55152/");
    driver.Manage().Window.Size = new System.Drawing.Size(1054, 790);
    driver.FindElement(By.CssSelector(".nav-item:nth-child(2) > a")).Click();
    driver.FindElement(By.Id("Name")).Click();
    driver.FindElement(By.Id("Name")).SendKeys("lesnoe chudo 2");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("+375364586523");
    driver.FindElement(By.CssSelector(".form-group:nth-child(4)")).Click();
    driver.FindElement(By.Id("price-usd")).SendKeys("20");
    driver.FindElement(By.Id("price-byn")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
  }
}
